export const properties = [
  { id: 1, title_key: 'properties.hakoneGora.title', subtitle_key: 'properties.hakoneGora.subtitle', summary_key: 'properties.hakoneGora.summary', price: 'N/A', cover: '/properties/covers/image1.jpg' },
  { id: 2, title_key: 'properties.yutoreroGarden.title', subtitle_key: 'properties.yutoreroGarden.subtitle', summary_key: 'properties.yutoreroGarden.summary', price: 'N/A', cover: '/properties/covers/image2.jpg' },
  { id: 3, title_key: 'properties.awajiSumoto.title', subtitle_key: 'properties.awajiSumoto.subtitle', summary_key: 'properties.awajiSumoto.summary', price: 'N/A', cover: '/properties/covers/image3.png' },
  { id: 4, title_key: 'properties.kataseEnoshima.title', subtitle_key: 'properties.kataseEnoshima.subtitle', summary_key: 'properties.kataseEnoshima.summary', price: 'N/A', cover: '/properties/covers/image4.jpg' },
  { id: 5, title_key: 'properties.izuIppeki.title', subtitle_key: 'properties.izuIppeki.subtitle', summary_key: 'properties.izuIppeki.summary', price: 'N/A', cover: '/properties/covers/image5.jpg' },
  { id: 6, title_key: 'properties.bosoShirahama.title', subtitle_key: 'properties.bosoShirahama.subtitle', summary_key: 'properties.bosoShirahama.summary', price: 'N/A', cover: '/properties/covers/image6.jpg' },
  { id: 7, title_key: 'properties.nagoyaSakae.title', subtitle_key: 'properties.nagoyaSakae.subtitle', summary_key: 'properties.nagoyaSakae.summary', price: 'N/A', cover: '/properties/covers/image7.jpg' },
  { id: 8, title_key: 'properties.bandaiAtami.title', subtitle_key: 'properties.bandaiAtami.subtitle', summary_key: 'properties.bandaiAtami.summary', price: 'N/A', cover: '/properties/covers/image8.jpg' },
  { id: 9, title_key: 'properties.nihombashi.title', subtitle_key: 'properties.nihombashi.subtitle', summary_key: 'properties.nihombashi.summary', price: 'N/A', cover: '/properties/covers/image9.jpg' },
  { id: 10, title_key: 'properties.hakataGrant.title', subtitle_key: 'properties.hakataGrant.subtitle', summary_key: 'properties.hakataGrant.summary', price: 'N/A', cover: '/properties/covers/image10.png' },
  { id: 11, title_key: 'properties.hamanako.title', subtitle_key: 'properties.hamanako.subtitle', summary_key: 'properties.hamanako.summary', price: 'N/A', cover: '/properties/covers/image11.jpg' },
  { id: 12, title_key: 'properties.nankiShirahama.title', subtitle_key: 'properties.nankiShirahama.subtitle', summary_key: 'properties.nankiShirahama.summary', price: 'N/A', cover: '/properties/covers/image12.png' },
  { id: 13, title_key: 'properties.biwako.title', subtitle_key: 'properties.biwako.subtitle', summary_key: 'properties.biwako.summary', price: 'N/A', cover: '/properties/covers/image13.png' },
  { id: 14, title_key: 'properties.izusan.title', subtitle_key: 'properties.izusan.subtitle', summary_key: 'properties.izusan.summary', price: 'N/A', cover: '/properties/covers/image14.png' },
  { id: 15, title_key: 'properties.kusatsu.title', subtitle_key: 'properties.kusatsu.subtitle', summary_key: 'properties.kusatsu.summary', price: 'N/A', cover: '/properties/covers/image15.png' },
  { id: 16, title_key: 'properties.atamiAjiro.title', subtitle_key: 'properties.atamiAjiro.subtitle', summary_key: 'properties.atamiAjiro.summary', price: 'N/A', cover: '/properties/covers/image16.jpg' },
  { id: 17, title_key: 'properties.echigoYuzawa.title', subtitle_key: 'properties.echigoYuzawa.subtitle', summary_key: 'properties.echigoYuzawa.summary', price: 'N/A', cover: '/properties/covers/image17.jpg' },
  { id: 18, title_key: 'properties.shinshuSalt.title', subtitle_key: 'properties.shinshuSalt.subtitle', summary_key: 'properties.shinshuSalt.summary', price: 'N/A', cover: '/properties/covers/image18.jpg' },
  { id: 19, title_key: 'properties.izuShuzenji.title', subtitle_key: 'properties.izuShuzenji.subtitle', summary_key: 'properties.izuShuzenji.summary', price: 'N/A', cover: '/properties/covers/image19.png' },
  { id: 20, title_key: 'properties.iseToba.title', subtitle_key: 'properties.iseToba.subtitle', summary_key: 'properties.iseToba.summary', price: 'N/A', cover: '/properties/covers/image20.png' },
  { id: 21, title_key: 'properties.yonagoKaike.title', subtitle_key: 'properties.yonagoKaike.subtitle', summary_key: 'properties.yonagoKaike.summary', price: 'N/A', cover: '/properties/covers/image21.jpg' },
  { id: 22, title_key: 'properties.narukoOnsen.title', subtitle_key: 'properties.narukoOnsen.subtitle', summary_key: 'properties.narukoOnsen.summary', price: 'N/A', cover: '/properties/covers/image22.png' },
  { id: 23, title_key: 'properties.numajiri.title', subtitle_key: 'properties.numajiri.subtitle', summary_key: 'properties.numajiri.summary', price: 'N/A', cover: '/properties/covers/image23.png' },
  { id: 24, title_key: 'properties.ashizuriMisaki.title', subtitle_key: 'properties.ashizuriMisaki.subtitle', summary_key: 'properties.ashizuriMisaki.summary', price: 'N/A', cover: '/properties/covers/image24.png' },
  { id: 25, title_key: 'properties.nasushiohara.title', subtitle_key: 'properties.nasushiohara.subtitle', summary_key: 'properties.nasushiohara.summary', price: 'N/A', cover: '/properties/covers/image25.jpg' }
]